apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: oq62eqwar-python
  janus-idp.io/tekton: oq62eqwar-python
  backstage.io/kubernetes-id: oq62eqwar-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oq62eqwar-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
